### ISSUE TITLE
[CICD] Currently not setting the version of the integration

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-prometheus#114]
When moving from 2.2.0 to 2.3.0 the integration version is no longer populated and left with a generic "dev".

This can create confusion and make debugging more difficult. 
Moreover we should add a flag to simply print this information and exit.

![Screen Shot 2020-12-09 at 4 19 56 PM](https://user-images.githubusercontent.com/43335750/101648716-6449bb80-3a3a-11eb-8e79-aac1df0d9e13.png)

**Comment by roobre** [comment]
Does this happen with the binary, the docker image, or both?

**Comment by paologallinaharbur** [comment]
The image is correctly tag, the binary (and the binary bundled) instead of the proper version simply has `dev`
