### ISSUE TITLE
Fails to run the integration in standalone=false when no definition_file folder is present

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/nri-prometheus#119]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
If the definition files folder is not present , the integration exits with a error.
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
The integration continues with no definition files loaded, as it would do for an exporter without definition file. 
## [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )
When the agent is installed no definition file folder is created so if you try to run POMI in standalone=false after a clean installation the error message will appear. 
## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )
The common scenario would be to run the integration having an exporter package installed that would provide the configuration file to run the integration and the definition files.

**Comment by roobre** [comment]
Is this issue still happening? I think we got rid of definitions in https://github.com/newrelic/nri-prometheus/pull/147.

**Comment by gsanchezgavier** [comment]
yes this is fixed
