### ISSUE TITLE
CI/CD: Helm chart bump job should report proper chart name and app version

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-prometheus#129]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Helm chart PR job reports placeholder or wrongly templatized values to the helm-charts repo, which causes PR openings to fail.

See https://github.com/newrelic/nri-prometheus/runs/1577554289?check_suite_focus=true

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

Job should report correct chart name and app version.

**Comment by paologallinaharbur** [comment]
@roobre is this fixed by the last PR?

**Comment by roobre** [comment]
Yes! Sorry, forgot to link the issue.
