### ISSUE TITLE
If SCRAPE_ENABLED_LABEL is provided, the scraper won't start

### ISSUE THREAD

**Issue by dragos-cojocari-ibm** [newrelic/nri-prometheus#13]
I have successfully setup both the infrastructure agent and the NR Scraper using the provided documentation. Both got installed and worked. I checked the link you provided and there is nothing there that does not work for me as long as the scrape label is unset.

For the Scraper I noticed that many metrics get discarded, included metrics we generate, because too many metrics are sent. To solve that I wanted to filter metrics sent from specific deployments using the LABEL property. Once I set the label property in the configuration for the scraper, the scraper stops working, it crashes at start with the following error:

```
time="2019-09-23T12:02:37Z" level=info msg="Starting New Relic Prometheus Integration version 0.10.3"
panic: runtime error: integer divide by zero
goroutine 86 [running]:
go.datanerd.us/p/fsi/nri-prometheus-scraper/internal/integration.(*prometheusFetcher).Fetch.func1(0xc000306b00, 0x1ee4398, 0x0, 0x0, 0xc0003670e0)
/go/src/go.datanerd.us/p/fsi/nri-prometheus-scraper/internal/integration/fetcher.go:168 +0x1c7
```

Removing the label property solves the issue. Also the value provided makes no difference. 

Note: I was pointed to this repo from https://support.newrelic.com/tickets/370148

**Comment by douglascamata** [comment]
Hi @dragos-cojocari-ibm! Thanks for the report. Let me explain to you what is happening:

1. You're running version 0.10.3 of the Prometheus integration
2. This version has a known bug in a piece of code that distributes the requests to each endpoint over time. When there are no endpoints, it divides by zero exactly here: https://github.com/newrelic/nri-prometheus/blob/master/internal/integration/fetcher.go#L178
3. In most recent versions, namely v1.0.1+, this piece of code prevents the problem from happening: https://github.com/newrelic/nri-prometheus/blob/5955eaf7c357b10a989d0ecadad42e5797e6deb7/internal/pkg/endpoints/kubernetes_test.go#L258

Can you try to upgrade the version of the Prometheus integration in the cluster and let me know if it fixes the issue, please?

**Comment by douglascamata** [comment]
Hi @dragos-cojocari-ibm! Thanks for the report. Let me explain to you what is happening:

1. You're running version 0.10.3 of the Prometheus integration
2. This version has a known bug in a piece of code that distributes the requests to each endpoint over time. When there are no endpoints, it divides by zero exactly here: https://github.com/newrelic/nri-prometheus/blob/master/internal/integration/fetcher.go#L178
3. In most recent versions, namely v1.0.1+, this piece of code prevents the problem from happening: https://github.com/newrelic/nri-prometheus/blob/v1.1.0/internal/integration/fetcher.go#L172

Can you try to upgrade the version of the Prometheus integration in the cluster and let me know if it fixes the issue, please?

**Comment by dragos-cojocari-ibm** [comment]
Thanks @douglascamata I installed the scraper using instructions in a doc file that were referring to https://download.newrelic.com/infrastructure_agent/integrations/kubernetes/kps-latest.yaml 

I now have used the ones from https://docs.newrelic.com/docs/integrations/prometheus-integrations/prometheus-kubernetes/new-relic-prometheus-openmetrics-integration-kubernetes#basic-troubleshooting and the deployment works

Thank you.

Btw, nice to see you are now ignoring Kube metrics.  The whole reason for starting on the LABEL path was to ensure only our metrics are scraped and leave the Kube ones to be handled by the NR infrastructure agent.
