### ISSUE TITLE
Currently new configs are not documented properly

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-prometheus#130]
We should improve documentation for the new configs (# workers,  emitter harvest period,  max number stored metrics).

We should update those in :
 - [x] [values of the helm chart](https://github.com/newrelic/helm-charts/blob/master/charts/nri-prometheus/values.yaml#L110)
 - [x] [documentation](https://docs.newrelic.com/docs/integrations/prometheus-integrations/install-configure-openmetrics/configure-prometheus-openmetrics-integrations#general-config)
 - [x] [sample yaml file](https://github.com/newrelic/nri-prometheus/blob/main/deploy/nri-prometheus.tmpl.yaml)
 - [x] [config file](https://github.com/newrelic/nri-prometheus/blob/main/configs/nri-prometheus-config.yml.sample) In this case note that standalone=false

**Comment by roobre** [comment]
Fixed in https://github.com/newrelic/helm-charts/pull/250, https://github.com/newrelic/nri-prometheus/pull/131, and doc changes.
