### ISSUE TITLE
POMI not discovering all endpoints of a service

### ISSUE THREAD

**Issue by bpschmitt** [newrelic/nri-prometheus#137]
## Description

I've configured POMI to point to the EKS API Server service URL:

```
targets:
   - description: EKS Control Plane
     urls: ["https://kubernetes.default.svc.cluster.local:443"]
```

I'm able to successfully chart the control plane metrics in NR, however, only one endpoint instance is being targeted when hitting the service.  NOTE: this data matches the `192.168.184.248` instance (yellow line) in the Grafana chart.  The `instance` attribute is missing in NR so I faceted by `scrapedTargetURL` instead.

![image](https://user-images.githubusercontent.com/9002169/105105548-e71e5700-5a79-11eb-9e2d-89441acf0439.png)

Here you can see the same query in Grafana, but both instances are present.

![image](https://user-images.githubusercontent.com/9002169/105105358-93137280-5a79-11eb-9d2b-2c1c843f5063.png)

Prometheus Server [uses an endpoint role](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#endpoints) in its scrape config to get a list of all endpoints belonging to a service and I believe we should use a similar strategy.  

## Workaround 

I can manually provide the endpoints to the POMI config, but this would be tedious to do for many clusters.

![image](https://user-images.githubusercontent.com/9002169/105105885-9fe49600-5a7a-11eb-8cc1-28d1fbd6154b.png)

If there's a better/easier way to configure this, please let me know - otherwise, we should explore options for improvement.

## Expected Behavior

Auto-discovery of service endpoints.

## Your Environment

- EKS Cluster running K8s v1.17.12
- POMI v2.4.0

**Comment by paologallinaharbur** [comment]
I believe it is related to the following known issue:
- https://github.com/newrelic/nri-prometheus/issues/27
- https://github.com/newrelic/nri-prometheus/issues/82

**Comment by paologallinaharbur** [comment]
If so I would close this and keep the old one

**Comment by bpschmitt** [comment]
thanks @paologallinaharbur.  Definitely seems related so I will close this one out.
