### ISSUE TITLE
Add ability to set scrape duration per target

### ISSUE THREAD

**Issue by duncaan** [newrelic/nri-prometheus#153]
## Is your feature request related to a problem? Please describe.
There are some targets that I want to scrape every 5m, not the default set on the nri-prometheus server.

## Feature Description
I would like to be able to set an annotation/label like this to tell nri-prometheus to scrape the target every 5m, instead of the server default.
`prometheus.io/duration: "5m"`

## Describe Alternatives
An alternative would be to scrape metrics from existing ServiceMonitor or PodMonitor resources which have these things already set.

## Priority
Really want

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.

We encourage community contributions and are happy to collaborate on design proposals and pull requests. See our PR guidelines in the README. If you have any further questions or comments about this, please let us know by replying to this issue.

**Comment by elixxx** [comment]
Any updates on this?
