### ISSUE TITLE
Add Histograms and Summary metrics names caveat to Documentation

### ISSUE THREAD

**Issue by carlossscastro** [newrelic/nri-prometheus#223]
Document on our public docs the caveats with metrics naming suffixes for histograms and summary metrics
https://prometheus.io/docs/concepts/metric_types/

**Comment by gsanchezgavier** [comment]
@carlossscastro could [this document](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/view-query-data/translate-promql-queries-nrql) close this issue or there is any particular point you mean in this issue ?
