### ISSUE TITLE
EMITTERS=stdout logs some default struct format

### ISSUE THREAD

**Issue by roblg** [newrelic/nri-prometheus#25]
The public docs suggest:

> To see the exact data that is being sent to the Metric API, set the EMITTERS environment variable to "api,stdout".

I set `EMITTERS=stdout`, and observed that the output was affected, but it looks like some sort of default output format for a struct:

```
time="2019-10-28T23:01:36Z" level=debug msg="Starting fetch process..." component=fetcher
time="2019-10-28T23:01:36Z" level=debug msg="fetching URL: {http   localhost:8080 /metrics  false  }" component=Fetcher target="localhost:8080"
time="2019-10-28T23:01:36Z" level=debug msg="Finished fetch process." component=fetcher
[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
```

I tried playing with the `verbose` flag in the config.yml, and setting emitters to `EMITTERS=api,stdout`, and neither had any effect on the logged default-struct output.

**Comment by davidbrota** [comment]
Hi @roblg,

I just tested version [v2.4.1](https://github.com/newrelic/nri-prometheus/releases/tag/v2.4.1) and the _stdout_ emitter is working fine.
