### ISSUE TITLE
bug with URL encoded params returned

### ISSUE THREAD

**Issue by pree** [newrelic/nri-prometheus#252]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

since release `2.10.0` using URL parameters doesn't work anymore. For example with `2.9.0` having the annotation `prometheus.io/path: /metrics?format=prometheus` worked, since `2.10.0` it queries it as `/metrics%3Fformat=prometheus`.

This was once solved in #46 but returned.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
`GET /metrics?format=prometheus`

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )
Set the annotation `prometheus.io/path: /metrics?format=prometheus`

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )
Running on AKS

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )
#46

**Comment by pree** [comment]
This is caused through #240

**Comment by paraenggu** [comment]
I'm just adding some additional context and details here (I was debugging this together with @pree ):

The `?format=prometheus` GET parameter is required to fetch Prometheus data from the [Vault metrics endpoint](https://www.vaultproject.io/api-docs/system/metrics), which defaults to JSON.

In case query parameters shouldn't be added to the path any more, another way is required to add GET parameters, such as an annotation similar to `prometheus.io/param`.

For this specific case (and maybe others as well) [Vault would also return the metrics in the Prometheus format](https://github.com/hashicorp/vault/blob/d341378c6353a9e0f776ca024215ea11be8672df/helper/metricsutil/metricsutil.go#L64-L66) if the Accept HTTP header `application/openmetrics-text` would be sent by nri-prometheus. Which doesn't seems to be the case, while [Prometheus itself is sending this header](https://github.com/prometheus/prometheus/blob/201aa3a964b68947346c5916695000f1ac24a468/scrape/scrape.go#L751). So it would probably be a good thing to consider as well.
