### ISSUE TITLE
Customizable targetName for Prometheus targets

### ISSUE THREAD

**Issue by juanjo-vlc** [newrelic/nri-prometheus#262]
## Is your feature request related to a problem? Please describe.
As we are using docker I'm always frustrated when all my targetNames are "exporter:9888" because I'm using the container name on the target definition.

## Feature Description
I want to specify the targetName independently from the URL

## Describe Alternatives
None

## Additional context
I'm running several docker-compose deployments and I like to reuse sections. As targetName is already added, reading it from the config.yml file should be easy. Or at least, use the already present description field. 

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
Nice to Have

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this feature request, we are unable to commit on a timeline to resolution. When committing to add a feature, we take into account the type of feature, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.
