### ISSUE TITLE
New Relic Prometheus OpenMetrics integration (Docker)

### ISSUE THREAD

**Issue by neha256** [newrelic/nri-prometheus#28]
I am trying to investigate how to monitor containers/container-host(docker) via newrelic. In our present scenario, all container-host instances are running the prometheus node_exporter, additionally they run the docker daemon metrics exporter. I came across the following documentation which states how to scrape these metrics in newrelic. https://docs.newrelic.com/docs/integrations/prometheus-integrations/prometheus-docker/new-relic-prometheus-openmetrics-integration-docker.

I need some help while configuring "nri-prometheus-latest.yaml "

1. the node_exporter and docker daemon exporting are running on their standard ports "port1" for node_exporter, and "port 2" for the docker daemon exporter. Where should I provide these ports in the config file?

**Comment by neha256** [comment]
Here goes my nri-prometheus-latest.yaml file:

---
apiVersion: v1
cluster_name: "Monitor_Docker_2"
kind: ServiceAccount
metadata:
  name: nri-prometheus
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: nri-prometheus
rules:
- apiGroups: [""]
  resources:
    - "nodes"
    - "nodes/metrics"
    - "nodes/stats"
    - "nodes/proxy"
    - "pods"
    - "services"
  verbs: ["get", "list", "watch"]
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nri-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nri-prometheus
subjects:
- kind: ServiceAccount
  name: nri-prometheus
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nri-prometheus
  labels:
    app: nri-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nri-prometheus
  template:
    metadata:
      labels:
        app: nri-prometheus
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: nri-prometheus
      containers:
      - name: nri-prometheus
        image: newrelic/nri-prometheus:1.2.2
        args:
          - "--configfile=/etc/nri-prometheus/config.yaml"
        ports:
          - containerPort: 9100
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nri-prometheus/
        env:
          - name: "LICENSE_KEY"
            value: ""
          - name: "BEARER_TOKEN_FILE"
            value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
          - name: "CA_FILE"
            value: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
      volumes:
        - name: config-volume
          configMap:
            name: nri-prometheus-cfg
---
apiVersion: v1
data:
  config.yaml: 
    # The name of your cluster. It's important to match other New Relic products to relate the data.

    # How often the integration should run. Defaults to 30s.
    # scrape_duration: "30s"

    # The HTTP client timeout when fetching data from endpoints. Defaults to 5s.
    # scrape_timeout: "5s"

    # Wether the integration should run in verbose mode or not. Defaults to false.
    verbose: false

    # Wether the integration should skip TLS verification or not. Defaults to false.
    insecure_skip_verify: false

    # The label used to identify scrapable targets. Defaults to "prometheus.io/scrape".
    scrape_enabled_label: "prometheus.io/scrape"

    # Whether k8s nodes need to be labelled to be scraped or not. Defaults to true.
    require_scrape_enabled_label_for_nodes: true

    # targets:
    #   - description: Secure etcd example
     #    urls: ["https://localhost:9100", "https://localhost:9323"]
    #     tls_config:
    #       ca_file_path: "/etc/etcd/etcd-client-ca.crt"
    #       cert_file_path: "/etc/etcd/etcd-client.crt"
    #       key_file_path: "/etc/etcd/etcd-client.key"

    # Proxy to be used by the emitters when submitting metrics. It should be
    # in the format [scheme]://[domain]:[port].
    # The emitter is the component in charge of sending the scraped metrics.
    # This proxy won't be used when scraping metrics from the targets.
    # By default it's empty, meaning that no proxy will be used.
    # emitter_proxy: "http://localhost:8888"

    # Certificate to add to the root CA that the emitter will use when
    # verifying server certificates.
    # If left empty, TLS uses the host's root CA set.
    # emitter_ca_file: "/path/to/cert/server.pem"

    # Whether the emitter should skip TLS verification when submitting data.
    # Defaults to false.
    # emitter_insecure_skip_verify: false

    # Histogram support is based on New Relic's guidelines for higher
    # level metrics abstractions https://github.com/newrelic/newrelic-exporter-specs/blob/master/Guidelines.md.
    # To better support visualization of this data, percentiles are calculated
    # based on the histogram metrics and sent to New Relic.
    # By default, the following percentiles are calculated: 50, 95 and 99.
    #
    # percentiles:
    #   - 50
    #   - 95
    #   - 99

    # transformations:
    #   - description: "General processing rules"
    #     rename_attributes:
    #       - metric_prefix: ""
    #         attributes:
    #           container_name: "containerName"
    #           pod_name: "podName"
    #           namespace: "namespaceName"
    #           node: "nodeName"
    #           container: "containerName"
    #           pod: "podName"
    #           deployment: "deploymentName"
    #     ignore_metrics:
    #       # Ignore all the metrics except the ones listed below.
    #       # This is a list that complements the data retrieved by the New
    #       # Relic Kubernetes Integration, that's why Pods and containers are
    #       # not included, because they are already collected by the
    #       # Kubernetes Integration.
    #       - except:
    #         - kube_hpa_
    #         - kube_daemonset_
    #         - kube_statefulset_
    #         - kube_endpoint_
    #         - kube_service_
    #         - kube_limitrange
    #         - kube_node_
    #         - kube_poddisruptionbudget_
    #         - kube_resourcequota
    #         - nr_stats
    #     copy_attributes:
    #       # Copy all the labels from the timeseries with metric name
    #       # `kube_hpa_labels` into every timeseries with a metric name that
    #       # starts with `kube_hpa_` only if they share the same `namespace`
    #       # and `hpa` labels.
    #       - from_metric: "kube_hpa_labels"
    #         to_metrics: "kube_hpa_"
    #         match_by:
    #           - namespace
    #           - hpa
    #       - from_metric: "kube_daemonset_labels"
    #         to_metrics: "kube_daemonset_"
    #         match_by:
    #           - namespace
    #           - daemonset
    #       - from_metric: "kube_statefulset_labels"
    #         to_metrics: "kube_statefulset_"
    #         match_by:
    #           - namespace
    #           - statefulset
    #       - from_metric: "kube_endpoint_labels"
    #         to_metrics: "kube_endpoint_"
    #         match_by:
    #           - namespace
    #           - endpoint
    #       - from_metric: "kube_service_labels"
    #         to_metrics: "kube_service_"
    #         match_by:
    #           - namespace
    #           - service
    #       - from_metric: "kube_node_labels"
    #         to_metrics: "kube_node_"
    #         match_by:
    #           - namespace
    #           - node
kind: ConfigMap
metadata:
  name: nri-prometheus-cfg
  namespace: default

**Comment by neha256** [comment]
[nri-prometheus.txt](https://github.com/newrelic/nri-prometheus/files/3825789/nri-prometheus.txt)

**Comment by neha256** [comment]
I also noticed while running the docker image, it gives me this error "time="2019-11-08T21:08:53Z" level=fatal msg="error occurred while running scraper" error="while getting configuration options: cluster_name is required and can't be empty""

Even though I have provided cluster_name

**Comment by lorgan3** [comment]
Are you trying to run this on just Docker or on Kubernetes? If you are using just Docker you can run the integration like this:

```
$ docker run -d --restart unless-stopped \
    --name nri-prometheus \
    -e LICENSE_KEY="YOUR_LICENSE_KEY" \
    -e VERBOSE=true \
    -v "$(pwd)/config.yaml:/config.yaml" \
    newrelic/nri-prometheus:1.1
```

The prometheus yaml file in the docs is the manifest for Kubernetes and just there as a second example on how to configure the integration and can't actually be used with just Docker. We should remove it, it's confusing. 
You should be able to use the first example in the docs though:
https://docs.newrelic.com/docs/integrations/prometheus-integrations/get-started/new-relic-prometheus-openmetrics-integration-docker#example-configuration-file

To define the containers you want to scrape you need to specify the container endpoint and the port in the config file.
```
targets:
  - description: example
     urls: ["<DOCKER_CONTAINER>:<CONTAINER_PORT>"]
```

Can you please tell us the command you are running to check why you are getting that cluster name error? (Don't forget to remove your license key before posting!)

**Comment by neha256** [comment]
Hello,

Thank you for you response. 

Actually I cannot use this command to run this integration due to restrictions not to mount volume on container host.

The way I am trying to run this integration is using a docker file and mentioning the details there. Creating image from that and then running container. Please find attached my testDockerFile.

I have updated my config.yaml file as you have instructed. It would be Great, if you could review this. In config.yaml, I have provided targets like: "https://ip:port number"

[testDockerFile.txt](https://github.com/newrelic/nri-prometheus/files/3831453/testDockerFile.txt)

[configTest1.txt](https://github.com/newrelic/nri-prometheus/files/3831466/configTest1.txt)

**Comment by neha256** [comment]
I created image providing the following attached config.yaml file
**When I run the image using docker run <image_id>, it gave me this error.
time="2019-11-11T14:15:43Z" level=fatal msg="while loading configuration" error="could not read configuration: While parsing config: yaml: line 22: mapping values are not allowed in this context"**
[configTest.txt](https://github.com/newrelic/nri-prometheus/files/3831692/configTest.txt)

**Comment by douglascamata** [comment]
Hi @neha256. 

I checked your config file and I found many weird characters in it with my text editor. Maybe they got added by accident before you attached the file, but please be careful with them as they might break the YAML reader in the code. See the picture below:

![image](https://user-images.githubusercontent.com/159076/68594395-badf7180-0497-11ea-80ab-45edd97dbced.png)


Also, I found that in your Dockerfile you look for the tagged version `1.2.3` and it doesn't exist. Our latest release is `1.2.2`.

> the node_exporter and docker daemon exporting are running on their standard ports "port1" for node_exporter, and "port 2" for the docker daemon exporter. Where should I provide these ports in the config file?

If you want to use custom ports in the config file, you have to add them as part of the url. For example, I got a fully working example with a configuration like this (notice the port `8080` for my fake node exporter url):

```yaml
cluster_name: "DockerMonitoringPilot"
verbose: false
insecure_skip_verify: false
scrape_enabled_label: "prometheus.io/scrape"
require_scrape_enabled_label_for_nodes: true
targets:
 - description: DockerMonitoringPrometheus
   urls: ["http://localhost/node_exporter_url:8080"]
```

**Comment by neha256** [comment]
Thanks. I updated my config.yaml and docker file and tried running integration with the updated settings. I am not sure whether the output is correct or not. In the output logs , it is giving the "scrapedTargetURL":"http://localhost:8080/metrics". In the config file I have provided target url as:    urls: ["http://localhost:9100"]. Please find below my updated config.yaml file:

cluster_name: "DockerMonitoringPilot"
verbose: false
insecure_skip_verify: false
scrape_enabled_label: "prometheus.io/scrape"
require_scrape_enabled_label_for_nodes: true
targets:
 - description: DockerMonitoringPrometheus
   urls: ["http://localhost:9100"]

**Comment by douglascamata** [comment]
@neha256 it looks good. You should check your data in New Relic using the chart builder and clicking on the button to switch from Events to Metrics.

If you don't see the data, I will need to have a better look into your logs.

**Comment by neha256** [comment]
@douglascamata I can see the result when I ran this query : SELECT *  FROM  MetricRaw where clusterName = 'DockerMonitoringPilot'

But it is giving me scrapedTargetUrl as the following even though I have provided 9100 as the port. here is the snippet from the output:

"promMetricType": "gauge",
            "scrapedTargetKind": "user_provided",
            "scrapedTargetName": "localhost:8080",
            "scrapedTargetURL": "http://localhost:8080/metrics",
            "targetName": "localhost:8080",

**Comment by douglascamata** [comment]
@neha256 did you push a new tag for this image and started the container again from the new tag?

**Comment by neha256** [comment]
Yes. Here goes my dockerFile:

ARG BASE_IMAGE_NAME="newrelic/nri-prometheus"
ARG BASE_IMAGE_VERSION="1.2.2"

FROM ${BASE_IMAGE_NAME}:${BASE_IMAGE_VERSION}

# Install jq
#RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y jq && rm -rf /var/lib/apt/lists/*

CMD ["echo, "Hello World...! from my first docker image"]

ENV LICENSE_KEY test123
#RUN mkdir -p $platform_scripts

ENV VERBOSE true
#RUN mkdir -p $platform_scripts

USER root
COPY ./config.yaml ./etc/nri-prometheus/config.yaml
RUN chmod +r ./etc/nri-prometheus/config.yaml

**Comment by neha256** [comment]
@douglascamata  I was able to make some progress. I rechecked my confog.yaml file. Not sure why it was not taking the last line which specifies the target urls. Now I was able to see something in Newrelic and logs related to port number 9100. But then also, I have some doubt, that why it is taking target name as 8080. Here is the snippet from Newrelic:

{
          "event": {
            "clusterName": "DockerMonitoringPilot",
            "endTimestamp": 1573490901344,
            "integrationName": "nri-prometheus",
            "integrationVersion": "1.2.2",
            "k8s.cluster.name": "DockerMonitoringPilot",
            "metricName": "nr_stats_fetches_total",
            "newrelic.source": "metricAPI",
            "nrMetricType": "gauge",
            "nr_stats_fetches_total": {
              "type": "gauge",
              "count": 1,
              "sum": 1,
              "min": 1,
              "max": 1,
              "latest": 1
            },
            "promMetricType": "gauge",
            "scrapedTargetKind": "user_provided",
            "scrapedTargetName": "localhost:8080",
            "scrapedTargetURL": "http://localhost:8080/metrics",
            "target": "localhost:9100",
            "targetName": "localhost:8080",
            "timestamp": 1573490900344
          }
        }

**Comment by douglascamata** [comment]
@neha256 this endpoint that you are seeing is exposed by our Prometheus integration itself. It contains its own metrics about how much data it's collecting and how it's performing. 

What query are you running to get this data? I recommend that you are read the official documentation about how to query data in this model: https://docs.newrelic.com/docs/data-ingest-apis/get-data-new-relic/metric-api/view-query-you-metric-data

**Comment by douglascamata** [comment]
Hi @neha256, are your problems and/or doubts solved? 😄

**Comment by alejandrodnm** [comment]
Hi @neha256 I'll be closing this issues since it has been a long time since the last activity, if you want to continue the discussion you can re-open it later.
