### ISSUE TITLE
Add support for `customAttributtes`

### ISSUE THREAD

**Issue by kang-makes** [newrelic/nri-prometheus#287]
## Is your feature request related to a problem?
All the integrations from New Relic has the idiom of having "customAttributes" and this integration/charts does not have them.

## Priority
Nice to Have

**Comment by paologallinaharbur** [comment]
There is [this](https://github.com/newrelic/nri-prometheus/blob/932318c2a54ac77c56803aa4da9580decf20f99e/internal/integration/rules.go#L16) allowing you to add custom attributes to metrics.

> // AddAttributesRule adds the Attributes to the metrics that match with MetricPrefix.

Not the best experience and different from the other charts, just posting in case someone looks for this issue :)
