### ISSUE TITLE
Metric type inferred override

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/nri-prometheus#294]
Metrics types are [inferred](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration#mapping) from the name on remote write but [calculated](https://github.com/newrelic/nri-prometheus/blob/main/internal/integration/telemetry_sdk_emitter.go#L196) from the type in POMI. This could make existing POMI users to change the metrics type if the metrics are not following the conventions. 

Investigate if a metric / relabel config can be added to the jobs to automatically add the metric type as label to avoiding the manual process.

**Comment by paologallinaharbur** [comment]
> Remote write functionality does not support sending metric metadata. Upstream Prometheus recently added support for propagation of metadata (metric type, unit, description, info) and this functionality will be supported in a future update to Prometheus Remote Write.

https://github.com/prometheus/prometheus/pull/6815

**Comment by paologallinaharbur** [comment]
Debugging prometheus code https://github.com/prometheus/prometheus/blob/78f264578722493dcd8bf25c43bde7865a18792f/scrape/scrape_test.go#L889-L889

Running test sending:
```
# TYPE test_metric counter
# HELP test_metric some help text
# UNIT test_metric metric
test_metric 1
# TYPE test_metric_no_help gauge
# HELP test_metric_no_type other help text
# EOF
```

when applying labels from the tests:
```
			// Hash label set as it is seen local to the target. Then add target labels
			// and relabeling and store the final label set.
			lset = sl.sampleMutator(lset)
```

This is what is available

[Uploading... Screen Shot 2022-05-11 at 11.23.45 AM.png]

**Comment by paologallinaharbur** [comment]
Internal discussion:
https://newrelic.slack.com/archives/CH292BVUZ/p1652198093247379

**Comment by paologallinaharbur** [comment]
An other PR looks promising, but it might take a while to see it merged https://github.com/prometheus/prometheus/pull/10312

**Comment by paologallinaharbur** [comment]
Asked for a different workaround https://github.com/prometheus/prometheus/issues/10684
