### ISSUE TITLE
Failures tests

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/nri-prometheus#297]
Simulate failures modes to check Prometheus behavior and how can be identified by an user (logs, metrics, pod status, etc) document in form of troubleshooting guide how the following points can be identified:
- targets side errors: timeout, internal fails, auth failure…
- remote write errors:
  - Check metrics retention mechanism under PRW endpoint fails. TSDB-WAL should hold metrics until they are sent to PRW

**Comment by paologallinaharbur** [comment]
Metrics that worth to keep an eye on https://grafana.com/blog/2021/04/12/how-to-troubleshoot-remote-write-issues-in-prometheus/

**Comment by alvarocabanas** [comment]
This is the outcome:
https://docs.google.com/document/d/197spWRcUX8XoMfbIK3p82947YEQL4UizK06Mra-P-2U/edit#

This is a dashboard:
https://staging.onenr.io/0X8woPlxvRx
