### ISSUE TITLE
Prometheus with Vault Integration

### ISSUE THREAD

**Issue by brianbao** [newrelic/nri-prometheus#30]
Hello,

I am trying to utilize this Docker image to scrape Prometheus metrics for a Vault cluster, which exposes the [/sys/metrics](https://www.vaultproject.io/api/system/metrics.html) endpoint. The only issue is that this endpoint is authenticated, which would require the scrape request to contain the `X-Vault-Token: ...` header.

It would be useful if we could specify a header to be set in the `config.yaml` file. Ideally this value may be dynamic -- in this case the Vault token expires every hour. I'm not sure how you'd want to handle this case. I'd be glad to submit a change upstream if you have a solution but don't have time to work on this.

Thanks!

**Comment by jorikvdwerf** [comment]
Hey @brianbao,

Thanks for your ticket! 
Right now we don't offer that functionality, but I do agree that it's a useful feature to add.

I will discuss your feature request with the team and we'll get back to you.

**Comment by brianbao** [comment]
Hey @jorikvdwerf, 

I did some digging and it looks like this was already basically implemented. The `config.yaml` file can specify a [`bearer_token_file`](https://github.com/newrelic/nri-prometheus/blob/99f4cd98e5353356ddced8cfef397b6197c410a2/internal/cmd/scraper/scraper.go#L39), which will read the file and append the `Authorization: Bearer {TOKEN}` header to the request, which the Vault Prometheus endpoint accepts.

In my digging it looks like there are actually a lot of parameters that went undocumented, such as [`metrics_api_url`](https://github.com/newrelic/nri-prometheus/blob/99f4cd98e5353356ddced8cfef397b6197c410a2/internal/cmd/scraper/scraper.go#L25) or [`insecure_skip_verify`](https://github.com/newrelic/nri-prometheus/blob/5955eaf7c357b10a989d0ecadad42e5797e6deb7/internal/pkg/endpoints/fixed.go#L24) on the `targets` config just to give two examples. It would be great if we could get these documented.

**Comment by douglascamata** [comment]
Hey @brianbao! Replying to your finding and feedback:

* We intentionally don't want to document `insecure_skip_verify` as it completely defeats the purpose of mutual TLS. 

* The metrics api url shouldn't need to be changed. Our code is smart enough to guess the region based on your license key. See here: https://github.com/newrelic/nri-prometheus/blob/a022884ea187367015dbe90edd48707d3dbddb0f/cmd/nri-prometheus/config_test.go. Is it somehow not working well for you?

* The `bearer_token_file` configuration was created to allow the metric fetching process to work on RBAC-protected Kubernetes clusters without changing a lot of the code. "Accidentally" it also works for your use case. This one I believe we can maybe transform into a feature, allowing you to configure bearer tokens per scraped URL maybe. WDYT?

**Comment by brianbao** [comment]
Thanks for your response @douglascamata. Everything you wrote makes sense.

Regarding the `bearer_token_file`, our only requirement is that there is some way to dynamically read a location for a token instead of having it hard-coded as a passed parameter, since these tokens can expire and will need to be refreshed. The code is already implemented to read the token file before every scrape request, so having the scraper configure a file per scraped URL as you described would be nice to have.

As it stands we are also perfectly fine using the `bearer_token_file` as is, so the feature may not be fully necessary.

**Comment by achupryn** [comment]
> Hey @brianbao! Replying to your finding and feedback:
> 
> * We intentionally don't want to document `insecure_skip_verify` as it completely defeats the purpose of mutual TLS.
> * The metrics api url shouldn't need to be changed. Our code is smart enough to guess the region based on your license key. See here: https://github.com/newrelic/nri-prometheus/blob/a022884ea187367015dbe90edd48707d3dbddb0f/cmd/nri-prometheus/config_test.go. Is it somehow not working well for you?
> * The `bearer_token_file` configuration was created to allow the metric fetching process to work on RBAC-protected Kubernetes clusters without changing a lot of the code. "Accidentally" it also works for your use case. This one I believe we can maybe transform into a feature, allowing you to configure bearer tokens per scraped URL maybe. WDYT?

Hello NR team, it will be great to have the possibility to configure bearer tokens per scraped URL. Can we reopen that issue or transform it into a feature request? Thanks
