### ISSUE TITLE
Does [audit: true] work?

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/nri-prometheus#300]
The sample config file includes an attribute of "audit" and the associated note is:

> # Audit mode logs the uncompressed data sent to New Relic. Use this to log all data sent.

However when I set this attribute to **true**; the log file contains no payloads.

## Config
cluster_name: "nocluster"
standalone: true
scrape_duration: "30s"
scrape_timeout: "5s"
verbose: true
debug: true
**audit: true**
targets:
  - description: publisher list
    urls: ["http://localhost:8080/metrics","http://192.168.1.170:8090/metrics"]

## Log Output
time="2022-05-20T20:17:03Z" level=debug msg="Starting fetch process..." component=fetcher
time="2022-05-20T20:17:03Z" level=debug msg="fetching URL: {http   localhost:8080 /metrics  false  }" component=Fetcher target="localhost:8080"
time="2022-05-20T20:17:03Z" level=debug msg="Finished fetch process." component=fetcher
time="2022-05-20T20:17:03Z" level=debug msg="Starting fetch process..." component=fetcher
time="2022-05-20T20:17:03Z" level=debug msg="fetching URL: {http   localhost:8080 /metrics  false  }" component=Fetcher target="localhost:8080"
2022/05/20 20:17:03.529875 {"body-length":3207,"event":"data post","url":"https://metric-api.newrelic.com/metric/v1/infra"}
2022/05/20 20:17:03.590671 {"body":{"requestId":"59d407c5-0001-b326-af3e-0180e31dd09a"},"event":"data post response","status":202}
time="2022-05-20T20:17:18Z" level=debug msg="fetching URL: {http   192.168.1.170:8090 /metrics  false  }" component=Fetcher target="192.168.1.170:8090"
time="2022-05-20T20:17:18Z" level=debug msg="Finished fetch process." component=fetcher
2022/05/20 20:17:18.528967 {"body-length":2770,"event":"data post","url":"https://metric-api.newrelic.com/metric/v1/infra"}
2022/05/20 20:17:18.658418 {"body":{"requestId":"e75c2c95-0001-ba6e-f29d-0180e31e0b6e"},"event":"data post response","status":202}

**Comment by GaPeppy** [comment]
I just built the binary from source.  I am running the binary local (no container) and I am seeing payloads. -?

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution because we are already working on a replacement for _nri-prometheus_ in containerized environments.

We encourage community contributions and are happy to collaborate on design proposals and pull requests. See our PR guidelines in the README. If you have any further questions or comments about this, please let us know by replying to this issue.
