### ISSUE TITLE
An invalid metric skip all the target

### ISSUE THREAD

**Issue by kang-makes** [newrelic/nri-prometheus#305]
## Description
Metrics in Prometheus must match this regex: `[a-zA-Z_:][a-zA-Z0-9_:]*` as the [documentation states](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels)

If a metric has an invalid character, the whole target is dropped instead of skipping that metric:
```
time="2022-05-26T14:53:29Z" level=warning msg="fetching Prometheus metrics: http://10.1.2.3:8024/actuator/prometheus (axonserver-0-0)" component=Fetcher error="text format parsing error in line 189: invalid escape sequence '\"'"
time="2022-05-26T14:53:29Z" level=warning msg="error while scraping target" component=Fetcher error="text format parsing error in line 189: invalid escape sequence '\"'"
```

For more context you can read the thread in the internal slack: https://newrelic.slack.com/archives/CP2EWSX7C/p1653928200917439

## Additional context
We use the same data model and parser that Prometheus use: https://github.com/newrelic/nri-prometheus/blob/406d893528aa04de36a4d672c4fc4ad268d656df/internal/pkg/prometheus/prometheus.go#L14

But we fail instead of simply logging the error: https://github.com/newrelic/nri-prometheus/blob/406d893528aa04de36a4d672c4fc4ad268d656df/internal/pkg/prometheus/prometheus.go#L69-L75

**Comment by gsanchezgavier** [comment]
Prometheus [scraper logic](https://github.com/prometheus/prometheus/blob/2381d7be57314df63c17291f22e5e770b44a70f3/scrape/scrape.go#L1481) expects no errors on parser, this makes it stateless, there is no procedure that has to be executed after in case an error is detected.
