### ISSUE TITLE
NRI-Prometheus not compatible with Open Metrics 1.0.0 / Spring-Boot

### ISSUE THREAD

**Issue by fieldju** [newrelic/nri-prometheus#313]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
NRI Prometheus will not scrape Springboot services.
NRI Prometheus only knows how to deserialize open-metrics `v0.0.1` but current impls are `1.0.0`

This header [here](https://github.com/newrelic/nri-prometheus/blob/main/internal/pkg/prometheus/prometheus.go#L40): 

`application/openmetrics-text;version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1`

Is out of step with [Prometheus official](https://github.com/prometheus/prometheus/blob/v2.36.2/scrape/scrape.go#L755):

`application/openmetrics-text;version=1.0.0,application/openmetrics-text;version=0.0.1;q=0.75,text/plain;version=0.0.4;q=0.5,*/*;q=0.1`

Springboot seems to return `application/openmetrics-text;version=1.0.0;charset=utf-8` regardless of the version specified in the accept header.

if you drop `application/openmetrics-text` from the accept springboot returns `text/plain;version=0.0.4;charset=utf-8` which nri-prometheus does know how to process.

But by default NRI-Prometheus throws `text format parsing error in line 2: invalid escape sequence '\"'` when processing `application/openmetrics-text;version=1.0.0`

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
I expect that NRI-Prometheus can consume `application/openmetrics-text;version=1.0.0` or configures the `Accept` header in a way that the Springboot Prometheus endpoint can handle.

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

:point_down: here is a test that reproduces the issue

```patch
Index: internal/pkg/prometheus/prometheus_test.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/internal/pkg/prometheus/prometheus_test.go b/internal/pkg/prometheus/prometheus_test.go
--- a/internal/pkg/prometheus/prometheus_test.go	(revision 5150e1e37fbd7d8fcd80f125a836a91c95ac2886)
+++ b/internal/pkg/prometheus/prometheus_test.go	(date 1656009750576)
@@ -11,7 +11,74 @@
 	"github.com/stretchr/testify/assert"
 
 	"github.com/newrelic/nri-prometheus/internal/pkg/prometheus"
+	dto "github.com/prometheus/client_model/go"
 )
+
+func TestGetDeserialization(t *testing.T) {
+	type test struct {
+		contentType string
+		contentBody string
+	}
+
+	tests := []test{
+		{
+			contentType: "text/plain;version=0.0.4;charset=utf-8",
+			contentBody: `# HELP process_cpu_usage The "recent cpu usage" for the Java Virtual Machine process
+# TYPE process_cpu_usage gauge
+process_cpu_usage{appName="Wormhole",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",replicaset="wormhole-cb4fd4d7f",version="1.26.15",} 0.008016032064128256
+# HELP jvm_memory_max_bytes The maximum amount of memory in bytes that can be used for memory management
+# TYPE jvm_memory_max_bytes gauge
+jvm_memory_max_bytes{appName="Wormhole",area="nonheap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="Metaspace",replicaset="wormhole-cb4fd4d7f",version="1.26.15",} -1.0
+jvm_memory_max_bytes{appName="Wormhole",area="nonheap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="CodeHeap 'non-nmethods'",replicaset="wormhole-cb4fd4d7f",version="1.26.15",} 5828608.0
+jvm_memory_max_bytes{appName="Wormhole",area="heap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="Tenured Gen",replicaset="wormhole-cb4fd4d7f",version="1.26.15",} 2.561343488E9
+jvm_memory_max_bytes{appName="Wormhole",area="nonheap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="CodeHeap 'non-profiled nmethods'",replicaset="wormhole-cb4fd4d7f",version="1.26.15",} 1.22916864E8
+jvm_memory_max_bytes{appName="Wormhole",area="heap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="Survivor Space",replicaset="wormhole-cb4fd4d7f",version="1.26.15",} 1.28057344E8
+jvm_memory_max_bytes{appName="Wormhole",area="nonheap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="CodeHeap 'profiled nmethods'",replicaset="wormhole-cb4fd4d7f",version="1.26.15",} 1.22912768E8
+jvm_memory_max_bytes{appName="Wormhole",area="nonheap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="Compressed Class Space",replicaset="wormhole-cb4fd4d7f",version="1.26.15",} 1.073741824E9
+jvm_memory_max_bytes{appName="Wormhole",area="heap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="Eden Space",replicaset="wormhole-cb4fd4d7f",version="1.26.15",} 1.024524288E9
+`,
+		},
+		{
+			contentType: "application/openmetrics-text;version=1.0.0;charset=utf-8",
+			contentBody: `# TYPE process_cpu_usage gauge
+# HELP process_cpu_usage The \"recent cpu usage\" for the Java Virtual Machine process
+process_cpu_usage{appName="Wormhole",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",replicaset="wormhole-cb4fd4d7f",version="1.26.15"} 0.008497079129049389
+# TYPE jvm_memory_max_bytes gauge
+# HELP jvm_memory_max_bytes The maximum amount of memory in bytes that can be used for memory management
+jvm_memory_max_bytes{appName="Wormhole",area="nonheap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="Metaspace",replicaset="wormhole-cb4fd4d7f",version="1.26.15"} -1.0
+jvm_memory_max_bytes{appName="Wormhole",area="nonheap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="CodeHeap 'non-nmethods'",replicaset="wormhole-cb4fd4d7f",version="1.26.15"} 5828608.0
+jvm_memory_max_bytes{appName="Wormhole",area="heap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="Tenured Gen",replicaset="wormhole-cb4fd4d7f",version="1.26.15"} 2.561343488E9
+jvm_memory_max_bytes{appName="Wormhole",area="nonheap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="CodeHeap 'non-profiled nmethods'",replicaset="wormhole-cb4fd4d7f",version="1.26.15"} 1.22916864E8
+jvm_memory_max_bytes{appName="Wormhole",area="heap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="Survivor Space",replicaset="wormhole-cb4fd4d7f",version="1.26.15"} 1.28057344E8
+jvm_memory_max_bytes{appName="Wormhole",area="nonheap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="CodeHeap 'profiled nmethods'",replicaset="wormhole-cb4fd4d7f",version="1.26.15"} 1.22912768E8
+jvm_memory_max_bytes{appName="Wormhole",area="nonheap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="Compressed Class Space",replicaset="wormhole-cb4fd4d7f",version="1.26.15"} 1.073741824E9
+jvm_memory_max_bytes{appName="Wormhole",area="heap",environment="staging",hostname="wormhole-cb4fd4d7f-jwvbl",id="Eden Space",replicaset="wormhole-cb4fd4d7f",version="1.26.15"} 1.024524288E9
+`,
+		},
+	}
+
+	for _, tc := range tests {
+		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+			_, _ = w.Write([]byte(tc.contentBody))
+			w.Header().Add("Content-Type", tc.contentType)
+		}))
+
+		mfs, err := prometheus.Get(http.DefaultClient, ts.URL)
+		assert.NoError(t, err)
+		assert.Len(t, mfs, 2)
+		assert.Contains(t, mfs, "process_cpu_usage")
+		processCpuUsage := mfs["process_cpu_usage"]
+		assert.Equal(t, "The \"recent cpu usage\" for the Java Virtual Machine process", *processCpuUsage.Help)
+		assert.Equal(t, dto.MetricType_GAUGE, *processCpuUsage.Type)
+
+		assert.Contains(t, mfs, "jvm_memory_max_bytes")
+		jvmMemoryMaxBytes := mfs["jvm_memory_max_bytes"]
+		assert.Equal(t, "The maximum amount of memory in bytes that can be used for memory management", *jvmMemoryMaxBytes.Help)
+		assert.Equal(t, dto.MetricType_GAUGE, *jvmMemoryMaxBytes.Type)
+
+		ts.Close()
+	}
+}
 
 func TestGet(t *testing.T) {
 	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
```

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

- https://github.com/micrometer-metrics/micrometer/issues/3242
- https://discuss.newrelic.com/t/nri-prometheus-scraping-issue/187067/4

**Comment by jonatan-ivanov** [comment]
Is NewRelic able to parse `openmetrics-text` or is it only able to parse `text/plain`?
If it is `text/plain`-only, it should not request `openmetrics-text` nor `*/*`, the value of the `Accept` header should be `text/plain;version=0.0.4`.

Sending back `1.0.0` is actually the right behavior in Spring Boot and NewRelic should not request `0.0.1`.
According to the [OpenMetrics Spec](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#overall-structure):
>The content type MUST be: application/openmetrics-text; version=1.0.0; charset=utf-8

And according to the Prometheus Java Client: https://github.com/prometheus/client_java/issues/702

See this issue: https://github.com/prometheus/prometheus/pull/9431

**Comment by roobre** [comment]
Hey @jonatan-ivanov,

The header we use for the request can be found here:
https://github.com/newrelic/nri-prometheus/blob/5edf5dacd697de00dc2818db7c47fdc89a5c385c/internal/pkg/prometheus/prometheus.go#L40

If I'm not mistaken, `nri-prometheus` supports `application/openmetrics-text;version=0.0.1`, and not `application/openmetrics-text;version=1.0.0`

> Springboot seems to return `application/openmetrics-text;version=1.0.0;charset=utf-8` regardless of the version specified in the accept header.

I believe this is a bug in the Springboot metric server, and should be fixed on that side. Removing `openmetrics-text;version=0.0.1` from `nri-prometheus`' accept header might break other exporters that only support `openmetrics-text;version=0.0.1`, for example.

Has this been brought to the attention of the Springboot maintainers?

**Comment by shakuzen** [comment]
As far as I understand, there is no `application/openmetrics-text` content type with version 0.0.1. That was something that existed only in the OpenMetrics specification before it released a version, which there has [only ever been one version released](https://github.com/OpenObservability/OpenMetrics/tags) at the time of this comment. From there, you can see there is no version 0.0.1 of the spec; there is only 1.0.0 which requires the content type to use version 1.0.0.

> Removing `openmetrics-text;version=0.0.1` from `nri-prometheus`' accept header might break other exporters that only support `openmetrics-text;version=0.0.1`, for example.

This is potentially true, but it is a bug that a producer can't handle an accept header with version 1.0.0 given the above and the discussion in the issues @jonatan-ivanov linked in his previous comment. As a consumer of OpenMetrics format, you can be lenient by having both versions in the accept header you send as was done in the Prometheus Server itself in https://github.com/prometheus/prometheus/pull/9431.

> I suspect this is a bug in the Springboot metric server

It would be a bug for an OpenMetrics producer to produce content that isn't version 1.0.0 while that is currently the only released version. Spring Boot has aligned with the behavior provided by the official Prometheus Java client library on handling accept headers and choosing the produced content type in https://github.com/spring-projects/spring-boot/issues/28130#issuecomment-933684234.

**Comment by roobre** [comment]
> there is no `application/openmetrics-text` content type with version 0.0.1

I was not aware of this, and it is certainly unfortunate. Thanks a lot for sharing this.

> This is potentially true, but it is a bug that a producer can't handle an accept header with version 1.0.0 given the above and the discussion in the issues @jonatan-ivanov linked in his previous comment.

I was originally under the impression that version `0.0.1` of `application/openmetrics-text` was, even if not released, sort of compatible with `text/plain;version=0.0.4`. After researching a bit on the prometheus code it seems that this is not correct.

Given this it seems that the right thing to do would be to strip `application/openmetrics-text` completely from our accept header, at least until we add support for it.

Thanks a lot for your explanation!
