### ISSUE TITLE
Adding support for custom label value in addition to scrape_enabled_label

### ISSUE THREAD

**Issue by buildwithjz** [newrelic/nri-prometheus#322]
## Is your feature request related to a problem? Please describe.
`nri-prometheus` OpenMetrics should allow us to set a custom label in addition to the label key when identifying scrapeable targets within a Kubernetes cluster

## Feature Description
While it is possible to set the `scrape_enabled_label` value in the nri-prometheus Helm chart to identify scrapeable targets based on custom labels, it is still a requirement that the label value is set to `true` in order for services to be discovered.

For example, setting a label of `prometheus.io/scrape: true` will allow the pods to be discovered, however the following will not:

`prometheus.io/scape: metrics`
`metrics_type: prometheus` (even with `scrape_enabled_label` set to `metrics_type`)

## Describe Alternatives
While it is possible to enable prometheus metrics on our services by adding this label, the majority of our services include `metrics_type: prometheus` *only* as a label to be discovered by our legacy prometheus monitor. It will be considered a huge enhancement for us if the OpenMetrics integration allowed us to set a custom label *value* field in its autodiscover functionality

## Additional context
Add any other context here.

## Priority
Really Want

**Comment by marcsanmi** [comment]
Hi,

I am afraid with the current integration this capability won't be considered. However, we are working on a new Prometheus Agent in Kubernetes solution by the end of the quarter that will allow you to use the relabel config to achieve this.

We are woking on an early adopters program for the new solution, if you are interested in joining it please let us know and we will happily share the details with you.

Thanks
