### ISSUE TITLE
Do we have an integration for scraping jmx metrics out of prometheus in Newrelic for dockers

### ISSUE THREAD

**Issue by neha256** [newrelic/nri-prometheus#34]

**Comment by douglascamata** [comment]
Hi @neha256. Our Prometheus Open-Metrics Integration does not export metrics in the JMX standard. It does export Prometheus standard metrics about itself and is automatically configured to scrape them from itself. 

Please let me know if this answers your question. 👍

**Comment by neha256** [comment]
Thanks @douglascamata . We figured that out and tried to convert jmx metrics into prometheus standard metrics but facing issues. This is what we did:
1. To convert the Jmx metrics into Prometheus standard metrics, we installed: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.12.0/jmx_prometheus_javaagent-0.12.0.jar
on our container for which we want the metrics to be scraped and sent to newrelic.
2. After that we used nri-prometheus, to send those metrics to newrelic.
3. But we are seeing this error on out console and also not seeing zookeeper/broker specific metrics in Newrelic Insights under Metrics tab.
**DEBU[0314] Finished fetch process.                       component=fetcher
2020/01/07 22:24:48.551799 json: error calling MarshalJSON for type telemetry.jsonString: invalid character ',' looking for beginning of value
2020/01/07 22:24:48.587518 {"body":{"requestId":"dcddf1f8-001e-b000-0000-016f821c45ca"},"event":"data post response","status":202}**
We are not sure why we are getting this error. If you could guide us on this.

**Comment by douglascamata** [comment]
Do you happen to have any NaNs or +/- Infinity in the Prometheus data? They can happen on summaries/histograms under certain circumstances.

There is a known problem with them in the version of the New Relic Telemetry SDK that we use in the current latest release: 1.2.2. A new version of the SDK with the fix was already released and we will update our imported version to include it.

**Comment by douglascamata** [comment]
@neha256 mind that unless you really want these metrics in the New Relic Metrics platform, you could use our JMX integration to avoid the metric convertion step: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/jmx-monitoring-integration

**Comment by neha256** [comment]
Yes, we know that and we prefer that. But we have been switching over from EC2 to dockers because of which there are some  restrictions due to which we cannot install infra agent on container host.

**Comment by neha256** [comment]
@douglascamata Could you please let us know by when you could provide us with the latest version, so that we can make some progress on this.

**Comment by douglascamata** [comment]
@neha256 sure! We're including this in our sprint starting next week.

So it's confirmed you have NaNs and Infinity in the data when the error appears?
