### ISSUE TITLE
question regarding scrape interval attribute in nri-prometheus-latest.yaml

### ISSUE THREAD

**Issue by neha256** [newrelic/nri-prometheus#38]
I have a question regarding an attribute in nri-prometheus-latest.yaml provided in the documentation- scrape interval . I wanted to know what is the time interval at which I am receiving insights into newrelic. And if we want to increase the interval, then which metric needs to be customized? # How often the integration should run. Defaults to 30s. # scrape_duration: "30s"  # The HTTP client timeout when fetching data from endpoints. Defaults to 5s. # scrape_timeout: "5s"

**Comment by douglascamata** [comment]
Hi @neha256! The `scrape_interval` setting is a way to customize how often the integration will "wake up" and fetch the metrics it's configured to. This will indeed change how often you see these metrics in New Relic, either in Insights or in the New Relic One platform. 

The `scrape_timeout` will configure the HTTP timeout of the requests sent to fetch the metrics. This doesn't affect how often the scraper will run.

If this answers your question, feel free to close the issue. 👍
