### ISSUE TITLE
Prometheus Federation

### ISSUE THREAD

**Issue by austince** [newrelic/nri-prometheus#40]
Hi there,

Is it possible to use this to federate specific metrics from a Prometheus server instead of scraping from each service? I'd like to set this up so we don't have to configure/ align multiple ways to scrape from services, and rather just maintain one scraping path to Prometheus, and then one path from Prometheus to New Relic.

I know one problem with this approach is that the Prometheus server doesn't store metric types -- how does New Relic handle metrics without types? Is this something that would be worth contributing?

**Comment by douglascamata** [comment]
Hi @austince, 

We don't have any specific feature related to Prometheus federation.

You can though configure this integration to fetch metrics from your Prometheus server federate endpoint. Like you mention, they don't store the metric types, so they will all come as `UNTYPED`. As a consequence, they will always be sent to New Relic as gauges (see https://github.com/newrelic/nri-prometheus/blob/master/internal/integration/fetcher.go#L328).  

I'm happy to discuss about it though. How do you think a proper Prometheus federation support could work? Or do you think this is enough?

**Comment by austince** [comment]
I think this is actually perfect, thanks for the quick reply @douglascamata. Some platforms ignore `UNTYPED` unless you manually map them to gauges. If I run into any problems implementing this solution, I'll post back with some suggestions. Thanks again!

**Comment by austince** [comment]
Hi @douglascamata, everything seems to be working well with federation! One thing that would be nice is the ability to turn off the service discovery component - is there an easy way to do that already? Thanks!

**Comment by douglascamata** [comment]
@austince unfortunately, we don't have a feature to disable the service discovery. I would recommend putting a random label there. Feel free to contribute with a PR if you want!

**Comment by austince** [comment]
Great, that's what I've done! Any good place you'd suggest starting if I'd like to make the PR?

**Comment by douglascamata** [comment]
@austince I think the `RunWithEmitters` function in the `scraper` package is a good start (https://github.com/newrelic/nri-prometheus/blob/master/internal/cmd/scraper/scraper.go#L109).

There you could add a configuration option to disable the discovery and skip some target retrievers (they are the concepts that execute the discovery).
