### ISSUE TITLE
ignore_metrics doesnt work?

### ISSUE THREAD

**Issue by bpschmitt** [newrelic/nri-prometheus#41]
I'm trying to make use of the ignore_metrics parameter but it doesn't seem to be working.  For example, I'm trying to **only** include `apiserver_requests_total` as a test (in addition to the other kube* stuff).  When I apply this to my cluster, I still see over 200 unique metric names showing up.  

Am I misunderstanding the use of this option?  

```
ignore_metrics:
  - except:
    - kube_hpa_
    - kube_daemonset_
    - kube_statefulset_
    - kube_endpoint_
    - kube_service_
    - kube_limitrange
    - kube_node_
    - kube_poddisruptionbudget_
    - kube_resourcequota
    - nr_stats
    - apiserver_request_total
```

**Comment by douglascamata** [comment]
Hi @bpschmitt! 

The `kube_` prefix metrics that are being included can represent a huge number of metrics, as there are many metrics exposed about each one of these resources (hpas, daemonset, etc). 

I recommend that you start allowing only `nr_stats` and `apiserver_request_total` and start opening up for more things little by little.

Also it's worth to mention that, depending on what there is running in the cluster, there might be other dimensional metrics being sent to New Relic. Even maybe another instance of nri-prometheus?

You can query `FROM Metric select uniques(metricName) where integrationName = 'nri-prometheus'` to verify.

**Comment by bpschmitt** [comment]
Revisiting this.  I'm now trying to **ignore** specific metrics [as outlined in our docs](https://docs.newrelic.com/docs/integrations/prometheus-integrations/install-configure-openmetrics/ignore-or-include-prometheus-metrics#example-ignore).  Here is the config being presented to my POMI pod.

```
/etc/nri-prometheus $ cat config.yaml
cluster_name: bschmitt-kops
require_scrape_enabled_label_for_nodes: true
ignore_metrics:
  - prefixes:
    - "http_"
```
POMI logs:

```
time="2020-08-31T21:55:15Z" level=info msg="Starting New Relic's Prometheus OpenMetrics Integration version 2.0.0"
```

Still seeing http_* metrics showing up for my cluster.  The ignore_metrics feature still does not seem to be working properly.  Halp! @jorik @douglascamata 

![image](https://user-images.githubusercontent.com/9002169/91774679-ffff9c00-ebae-11ea-9faf-e11ee56dcd61.png)

**Comment by gsanchezgavier** [comment]
Hi @bpschmitt  `ignore_metrics:` is part of `transformations:`  object. Please try using the following:
```yaml
transformations: 
  - description: "Description" 
    ignore_metrics:
      - prefixes:
        - "http_"
```
I think the Docs examples could lead you to this issue. I will propose a change there.

**Comment by gsanchezgavier** [comment]
I'll close this issue, docs are in process to be updated , feel free to reopen it for any other question, thanks!
