### ISSUE TITLE
summary type metrics are not showing up.

### ISSUE THREAD

**Issue by fieldju** [newrelic/nri-prometheus#53]
I've noticed that none of the summary type metrics from the following scrape (all scrapes on the pods in my cluster) do not show up in NR1/insights

https://gist.github.com/fieldju/90cf92976358853245ba1eb99a94523c#file-prom-scrap-txt-L413-L422

Again I am not seeing any of the sum or count metrics from Micrometer timers.

```
.*-seconds_count
.*_seconds_sum
```

This post says that summaries were coming:
https://github.com/newrelic/nri-prometheus/issues/14#issuecomment-535047091

This pull request says it was adding support:
https://github.com/newrelic/nri-prometheus/pull/15

I am running 1.5.0 of this integration

```
Controlled By:  ReplicaSet/nri-prometheus-67ff84fbf8
Containers:
  nri-prometheus:
    Container ID:  docker://4c7ea34dc7ac0658d8b3ec45c134da583c20f3fff9abfc038685bdfbc052b02b
    Image:         newrelic/nri-prometheus:1.5.0
```

**Comment by fieldju** [comment]
Maybe related to https://github.com/newrelic/nri-prometheus/issues/45

**Comment by douglascamata** [comment]
Hey @fieldju! 

Currently this integration **does not** pull the `_count` or `_sum` metrics of a Summary. Both are not in the [New Relic specs for percentiles](https://github.com/newrelic/newrelic-exporter-specs/blob/master/Guidelines.md#percentiles).

**Comment by fieldju** [comment]
I haven't had a chance to dig in yet but can it be patched?

This seems to be we're latency data is stored for http requests with
Springboot and Micrometer.

Cheers,

Justin

**Comment by fieldju** [comment]
But they are of type `summary`

```
# HELP controller_invocations_seconds  
# TYPE controller_invocations_seconds summary
controller_invocations_seconds_count{account="None",applicationName="clouddriver",armoryAppVersion="2.20.1",cause="None",controller="MetricsController",customerEnvName="fieldju-dev",customerName="armory",hostname="spin-clouddriver-d6f48976b-dwmpf",lib="armory-observability-plugin",libVersion="v1.0.0-RC13",method="getMetrics",ossAppVersion="6.9.2-20200606020017",region="None",spinnakerRelease="1.20.5",status="2xx",statusCode="200",success="true",} 2108.0
controller_invocations_seconds_sum{account="None",applicationName="clouddriver",armoryAppVersion="2.20.1",cause="None",controller="MetricsController",customerEnvName="fieldju-dev",customerName="armory",hostname="spin-clouddriver-d6f48976b-dwmpf",lib="armory-observability-plugin",libVersion="v1.0.0-RC13",method="getMetrics",ossAppVersion="6.9.2-20200606020017",region="None",spinnakerRelease="1.20.5",status="2xx",statusCode="200",success="true",} 40.766105613
controller_invocations_seconds_count{account="None",applicationName="clouddriver",armoryAppVersion="2.20.1",cause="None",controller="ApplicationsController",customerEnvName="fieldju-dev",customerName="armory",hostname="spin-clouddriver-d6f48976b-dwmpf",lib="armory-observability-plugin",libVersion="v1.0.0-RC13",method="list",ossAppVersion="6.9.2-20200606020017",region="None",spinnakerRelease="1.20.5",status="2xx",statusCode="200",success="true",} 12513.0
controller_invocations_seconds_sum{account="None",applicationName="clouddriver",armoryAppVersion="2.20.1",cause="None",controller="ApplicationsController",customerEnvName="fieldju-dev",customerName="armory",hostname="spin-clouddriver-d6f48976b-dwmpf",lib="armory-observability-plugin",libVersion="v1.0.0-RC13",method="list",ossAppVersion="6.9.2-20200606020017",region="None",spinnakerRelease="1.20.5",status="2xx",statusCode="200",success="true",} 28.909571336
controller_invocations_seconds_count{account="None",applicationName="clouddriver",armoryAppVersion="2.20.1",cause="None",controller="PrometheusScrapeController",customerEnvName="fieldju-dev",customerName="armory",hostname="spin-clouddriver-d6f48976b-dwmpf",lib="armory-observability-plugin",libVersion="v1.0.0-RC13",method="scrape",ossAppVersion="6.9.2-20200606020017",region="None",spinnakerRelease="1.20.5",status="2xx",statusCode="200",success="true",} 2109.0
controller_invocations_seconds_sum{account="None",applicationName="clouddriver",armoryAppVersion="2.20.1",cause="None",controller="PrometheusScrapeController",customerEnvName="fieldju-dev",customerName="armory",hostname="spin-clouddriver-d6f48976b-dwmpf",lib="armory-observability-plugin",libVersion="v1.0.0-RC13",method="scrape",ossAppVersion="6.9.2-20200606020017",region="None",spinnakerRelease="1.20.5",status="2xx",statusCode="200",success="true",} 14.247636965
controller_invocations_seconds_count{account="None",applicationName="clouddriver",armoryAppVersion="2.20.1",cause="None",controller="CredentialsController",customerEnvName="fieldju-dev",customerName="armory",hostname="spin-clouddriver-d6f48976b-dwmpf",lib="armory-observability-plugin",libVersion="v1.0.0-RC13",method="list",ossAppVersion="6.9.2-20200606020017",region="None",spinnakerRelease="1.20.5",status="2xx",statusCode="200",success="true",} 2099.0
controller_invocations_seconds_sum{account="None",applicationName="clouddriver",armoryAppVersion="2.20.1",cause="None",controller="CredentialsController",customerEnvName="fieldju-dev",customerName="armory",hostname="spin-clouddriver-d6f48976b-dwmpf",lib="armory-observability-plugin",libVersion="v1.0.0-RC13",method="list",ossAppVersion="6.9.2-20200606020017",region="None",spinnakerRelease="1.20.5",status="2xx",statusCode="200",success="true",} 0.916802292
```
NewRelic Summary types do support `min, max, sum, count`, should the summaries not be mapped to new relic summaries and include all the critical data?

**Comment by douglascamata** [comment]
Hey @fieldju! This should be improved by #54, which is in the `v2.0.0-rc1` pre-release. [This commit](https://github.com/newrelic/nri-prometheus/commit/ca6e6fce0e7533db173fa85aa54c604bba77a1ce) contains more information about the changes being done to histograms and summaries.

I invite you to try this RC release and please tell us if it fixes this problem.

**Comment by fieldju** [comment]
> Hey @fieldju! This should be improved by #54, which is in the `v2.0.0-rc1` pre-release. [This commit](https://github.com/newrelic/nri-prometheus/commit/ca6e6fce0e7533db173fa85aa54c604bba77a1ce) contains more information about the changes being done to histograms and summaries.
> 
> I invite you to try this RC release and please tell us if it fixes this problem.

This is Awesome, I will check this out.

I had no idea if or when this was coming, so I [refactored the code I was working](https://github.com/armory-plugins/armory-observability-plugin/commit/d40afc592a0c82c887fde67101c447cdb0a5c76b) on to use a [micrometer composite registry](https://micrometer.io/docs/concepts#_composite_registries) and take advantage of the [New Relic Micrometer Registry](https://github.com/newrelic/micrometer-registry-newrelic) to send metrics to NR and Prometheus. This does double the memory requirements if both integrations are enabled, so still might want the NRI Prom Scrapper over the Micrometer registry 🤔 . 

However this will only work for our Java services, we will be wanting this integration for our Golang microservices so that we can instrument the application with a vendor-agnostic metrics library that at least supports prometheus and have metrics locally with Grafana/Prometheus and NR at the same time.
