### ISSUE TITLE
feature:  support for replicas

### ISSUE THREAD

**Issue by 0011blindmice** [newrelic/nri-prometheus#56]
_I apologize if this isn't the right format or location for a feature request, but I didn't see any clear guidance on how to submit one._

## Problem statement
Currently, the nri-prometheus deployment doesn't have any form of quorom or primary/secondaries.  This prevents users from properly using replicas to manage additional load due to increases in scrapes and metric counts.

## Current solution
In order to handle situations with overload on the nri-prometheus pod, users need to create separate deployments with unique targets and/or scrape tags, manually slicing up their overall metric workload.  Otherwise, the replicas will all try to scrape the same metrics and offer no real gain

## Suggestion
Implement a solution allowing nri-prometheus to support multiple replicas and intelligently divide up workloads so that users do not need to maintain separate deployments targeting unique endpoints.

**Comment by jfjoly** [comment]
Thanks for taking the time to explain the problem @0011blindmice , this is very helpful!

**Comment by aocheretnoy** [comment]
Could you please share this information with me?

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution for more than a year. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.
