### ISSUE TITLE
Make HarvestTimeout configurable

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-prometheus#81]
## Is your feature request related to a problem? Please describe.
Sometimes the harvest takes more time than the default timeout, the SDK provides a parameter to increase/descrease such timeout that we are not leveraging

## Feature Description
Make `HarvestTimeout` configurable

## Priority
[Nice to Have]

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
