### ISSUE TITLE
Issues when not running in standalone mode

### ISSUE THREAD

**Issue by davidbrota** [newrelic/nri-prometheus#83]
when `standalone` is `false`:

- the default emitter should be `infra-sdk`
- the `definition_files_path` config option should have a default value 
- if you don't provide the definition files, a debug log message shows up for every metric

```
time="2020-09-23T14:22:12Z" level=debug msg="time=\"2020-09-23T14:22:12Z\" level=debug msg=\"failed to map metric to entity. using 'host' entity\" error=\"no spec files for service: ravendb\"" component=integrations.runner.Group integration_name=nri-prometheus
```

which spams the debug log and it's quite annoying. We should only log once per namespace.

**Comment by gsanchezgavier** [comment]
the PR has been merged
