### ISSUE TITLE
Modify POMI to report new instrumentation attributes:

### ISSUE THREAD

**Issue by ardias** [newrelic/nri-prometheus#93]
We need to report these new attributes:
- instrumentation.provider: newRelic
- instrumentation.name: nri-prometheus
- instrumentation.version: x.y.z

This will be done in the SDK but we also need to update the names of the vars in POMI and add the provider attribute

**Comment by paologallinaharbur** [comment]
Currently the payload returns already to the agent:
```json
"integration":{"name":"nri-prometheus","version":"dev"}
```
That then is transformed into:
```json
"integrationName": "nri-prometheus",
"integrationVersion": "dev",
```
Do we really need the new fields?

**Comment by paologallinaharbur** [comment]
Possible approaches:
 - Follow the POMI approach and add that info directly as attributes of the metric (but then the same change is needed in different integrations)

 - Modify the SDK adding the attributes to the metric by default

 - Simply pass from the SDK "integration":{"name":"nri-prometheus","version":"dev","provider":"newRelic"} to the agent. In this case the Agent should be modified to add the new attributes to the metric

At first I included them in the metadata of the entity and it “works”, but we came to the conclusion that add such info to the metadata is wrong

**Comment by paologallinaharbur** [comment]
Talking with Carlos and Julien we reached an agreement on changing it on the agent side adding the data in the common.attributes field.

No POMI or SDK change will be needed.
Only for the metrics we are currently sending with `standalone=true`
